### PR TITLE
Default to page title if no text is provided for Twitter

### PR DESCRIPTION
**Pull request by mickeywu**

### CODE REVIEW

**Comment by wouldgo** [comment]
@45kb LGTM

**Comment by 45kb** [comment]
Hi all, thank you @mickeywu but, actually, this looks useless to me, i explain my reasons/doubts:

1 - <meta> are usually preferred to <title>
2 - if no text to share means you do not pass text and it's wrong, you could always do $scope.title = $window.document.title and pass it to the sharer

Don't you agree?

**Comment by 45kb** [comment]
Actually what i mean is that, this PR could be perfect if applyed to <meta> tags instead of <title> and if the same is applyed to all the module providers and not only twitter :dancers:  @mickeywu 

What you think guys?

**Comment by wouldgo** [comment]
Actually @45kb you're right I didn't notice very well where the code is in relation of the others providers. :sheep:

**Comment by TheWrongAlice** [comment]
Are you really sure that this behavior should be standard for all providers? (or am I misunderstanding?)
It seems to me that some people might want to share to some media without titles...

**Comment by 45kb** [comment]
@TheWrongAlice i agree, we discussed this with @wouldgo  and actually the very best could be to move all the logic to a new attribute, example:  ```socialshare-meta="TRUE | FALSE"``` ( by default is FALSE)

That way you can specify if you want to inherit and share < meta > inside text......

**Comment by TheWrongAlice** [comment]
So if you set `socialshare-meta=true` (I would call it something else btw) then that means we use <title> and <meta> tags to auto-populate field values?

**Comment by 45kb** [comment]
it could be yes, <title> + <meta desc> in text field :)

**Pull request closed without merging**
