### PR TITLE
Added option to NOT url encode on linkedin

### PR DESCRIPTION
**Pull request by xelhark**
I know it sucks right?

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @xelhark  thank you so much, could you just please extend the attribute to all the providers, not only linkedin.

Let me know so we can merge it, thanks!

**Comment by xelhark** [comment]
Sure, I didn't because this is actually useless, I'll do it in a couple of
hours
Il 16/lug/2015 15:15, "Filippo" <notifications@github.com> ha scritto:

**Comment by 45kb** [comment]
@xelhark awesome, much appreciated man.
Even if it is not of great importance may be convenient in certain use cases, only for you know ... ;)

**Comment by TheWrongAlice** [comment]
Useless? What do you mean? :D

**Comment by 45kb** [comment]
@xelhark  any news?

I was thinking about the new option that probably is not correct, we just need to internally (the directive itself) should encode or not urls depending on providers, some allows encoding some others not, its just a matter of testing which.

Don't you agree?

**Comment by TheWrongAlice** [comment]
I see no point in letting users decide this

**Comment by xelhark** [comment]
Uhm honestly I'm not sure. As far as I know, urls should always be encoded,
so when LinkedIn only accepts urls that are not encoded, it's a bug on
their part.

If you add this option internally, then you're forced to update this right
when LinkedIn fixes this bug. If this happens on other providers, you can
see how this becomes hardly mantainable, so giving the option to the user
would allow them to have a working app without having to wait for us to
update it, right?

2015-07-21 10:43 GMT+02:00 Filippo <notifications@github.com>:

**Comment by TheWrongAlice** [comment]
That's not really solving the problem though, as the user would have to do the update instead

**Comment by 45kb** [comment]
@xelhark  Actually, we should not care about if it's third parties issue, if is there some way to fix it to make the module work so let's do that ;)

Seriously, better to fix this internally provider by provider, it's just a matter of testing them ;)

**Comment by xelhark** [comment]
@TheWrongAlice not if the option can be just changed as an attribute (for example, `socialshare-encode-url='true'` ). In this case the user can have a working version without having to upgrade anything

**Comment by 45kb** [comment]
@xelhark  No problems if linkedin makes changes, whenever a provider will make changes it's up to us to mantain the module up to date ;)

**Comment by xelhark** [comment]
Ok then, I'll be testing them and see how they work.

**Comment by 45kb** [comment]
AWESOME! thank you a lot, realy.

**Pull request closed without merging**
