### PR TITLE
fixes #107: Added resize switch to .open()

### LINKED ISSUE #107: Unable to resize share popup in IE
It's not possible to resize the share dialog when using IE. Some users reported cropped share dialogs when using the XING share button.

I'll make a pull request to fix this.

### PR DESCRIPTION
**Pull request by posixpascal**
Should I make this optional/configurable? 
Most browsers except IE are ignoring "resizable=no" and use "resizable=yes" by default.

### CODE REVIEW

**Comment by 45kb** [comment]
Awesome job, yes to be merged we need a new attribute for this `socialshare-popup-resize` and it must be configurable via configProvider also 👍

**Comment by 45kb** [comment]
@posixpascal  sorry, i forgot to ping you, i answered you above.

**Comment by posixpascal** [comment]
Oh hey, no problem. I'll update my pull request later :)

**Comment by 45kb** [comment]
Thank you a lot.

**Comment by 45kb** [comment]
Released with latest 2.1.8 version, thank you for spotting this out!

**Pull request closed without merging**
