### PR TITLE
Added German social media platform Xing

### PR DESCRIPTION
**Pull request by DonHaron**

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @DonHaron  great work looks ok to me, can you just tell me what the follow_url does?

**Comment by DonHaron** [comment]
Hey @45kb 
This is the URL of the Xing page which will be suggested to you for you to follow after sharing the link.
See: https://dev.xing.com/plugins/follow/docs & https://dev.xing.com/plugins/share_button/docs (Follow link to "custom design")

**Comment by 45kb** [comment]
Thank you a lot, i am rewriting some of the README to fill this informations  :+1:

**Comment by DonHaron** [comment]
You're welcome. Thank you for the awesome plugin :)

**Comment by 45kb** [comment]
Glad if it helps, feel free to PR if you any other solution :)

**Comment by DonHaron** [comment]
Oh, will you just do a new version and bower release with this change anytime soon?

**Comment by 45kb** [comment]
Yes, in a while :)

**Comment by DonHaron** [comment]
Great! Gonna use it for our project, will be glad if i can just use the
bower package :)

2015-11-10 12:29 GMT+01:00 Filippo <notifications@github.com>:

**Comment by 45kb** [comment]
Shipped, you can update your module :) thank you a lot 

https://github.com/720kb/angular-socialshare/releases/tag/0.1.16

**Comment by DonHaron** [comment]
Thanks, you're really unbelievably quick ;)

**Pull request merged**
