### PR TITLE
fixes #103: added provider for odnoklassniki

### LINKED ISSUE #103: Provider for Odnoklassniki

### PR DESCRIPTION
**Pull request by edencore**

### CODE REVIEW

**Comment by 45kb** [comment]
Oh awesome!!

Thank you a lot, i will review a little and quite for sure merge.

**Comment by edencore** [comment]
Thank you in advance! Please tell me if I should fix something or do some additional work on this.

**Comment by 45kb** [comment]
Did you test this both using Provider config and attributes ?

**Comment by edencore** [comment]
No, I didn't to be honest. I used manageVkShare as a reference, so I supposed that everything must be ok.

**Comment by 45kb** [comment]
Ok, the code looks really ok, i will merge and test a little, then later release a new version

Thanks for your time!

**Pull request merged**
