### PR TITLE
Added Telegram provider

### PR DESCRIPTION
**Pull request by edencore**
Someone asked for this and I think that messenger deserves own provider in this module 😏

### CODE REVIEW

**Comment by 45kb** [comment]
@edencore Absolutely! thanks for your time, i will test everything and release it 👍

**Comment by 45kb** [comment]
📦  https://github.com/720kb/angular-socialshare/releases/tag/2.1.6

**Comment by 45kb** [comment]
@edencore  doesn't work in a popup window? :)

**Comment by edencore** [comment]
@45kb I'm not sure, to be honest. For me that link redirects to desktop application, so I think that popup window is not required. But if you want, I can try to work with popups

**Comment by 45kb** [comment]
@edencore Yes please, on desktop browsers a popup is preferable :)

**Comment by edencore** [comment]
@45kb okay! I will look into this, but not today probably

**Comment by 45kb** [comment]
@edencore Absolutely no problems! Appreciated a lot your help,i set this https://github.com/720kb/angular-socialshare/issues/111 just as a reminder for all 👍

**Pull request merged**
