### PR TITLE
Share to Facebook using Feed Dialog

### PR DESCRIPTION
**Pull request by TheWrongAlice**
Added additional provider called `facebook-alt` that allows a new way of sharing content to Facebook, using the Facebook Feed Dialog: https://developers.facebook.com/docs/sharing/reference/feed-dialog/v2.4

*Why?*
Because it is so much more customizable than the current implementation which uses sharer.php.
For example, the reason I did this was because I wanted to specify a custom image (rather than having Facebook crawl the link I am sharing and guessing which image is more important), and now I can do this using the `socialshare-media` attribute.

*Considerations*
Perhaps instead of adding an additional provider, I should have replaced the current one? It should be possible to do so, with 100% backwards compatibility. Please let me know if you would rather have me do that before merging, I would be happy to make this or any other adjustments :)

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @TheWrongAlice  this looks promising :)
The feed looks way better than the old sharer , the best thing could be to differentiate facebook sharer and feed leaving the same provider name, so for example:
```
<a socialshare socialshare-provider="facebook" socialshare-provider-mode="feed || sharer">
Share on fb
</a>```

And if no socialshare-provider-mode="" specified the default is sharer.

Do you agree? :dancers:

**Comment by TheWrongAlice** [comment]
Agree on the `socialshare-type` thing @45kb !
But don't you want the feed as default setting then, as you said it looks better? :p
Your repo, your call - I can work with it either way. I'll commit the changes later today most likely :)

**Comment by 45kb** [comment]
@TheWrongAlice  thanks Alice, actually having _sharer_ as default option is better, because the actual user expectation is to see the sharer popup since it's the most used atm.

Anyway don't worry switching from a default one to another will be not a problem i guess.

Much appreciated, seriously :+1:

**Comment by TheWrongAlice** [comment]
Alright, have a look now :)

**Comment by 45kb** [comment]
Hey, it's an awesome job, thank you a lot, i am going to merge test and release a new version!

**Comment by TheWrongAlice** [comment]
:D :D :D

**Comment by NetanelBasal** [comment]
The dialog is not closing after the share and i does not see the share on my facebook,

**Comment by 45kb** [comment]
@NetanelBasal  could you please show your html part thank you

**Comment by NetanelBasal** [comment]
```html

    <a href="#"
       socialshare
       socialshare-provider="facebook"
       socialshare-via="myAppID"
       socialshare-type="feed"
       socialshare-text="{{title}}"
       socialshare-redirect-uri="my website url"
       socialshare-url="my website url"
        >
        <i class="fa fa-facebook"></i>
    </a>
```

**Comment by 45kb** [comment]
@NetanelBasal  that's not a module problem, check, this works great:
```
<button class="btn btn-medium font-bold"
      socialshare
      socialshare-provider="facebook"
      socialshare-type="feed"
      socialshare-via="145634995501895"
      socialshare-media="http://720kb.net/assets/img/720kb-fb.png"
      socialshare-text="720kb"
      socialshare-caption="720kb is enough"
      socialshare-url="http://720kb.net"
      socialshare-redirect-uri="https://developers.facebook.com/tools/explorer"
      socialshare-popup-height="300"
      socialshare-popup-width="400"
      socialshare-trigger="click" >
      <i class="fa fa-facebook"></i> Share on Facebook (feed dialog)
    </button>```

You are probably bad formatting urls or data you pass to the dialog, then, the popup can't be closed from the socialshare side, if it doesn't close it's a facebook problem.

**Comment by NetanelBasal** [comment]
But also in linkedin the dialog show me a message that the link is shared successfully but i does not see the post in my wall (also in facebook)... what do you think the problem?

**Comment by 45kb** [comment]
@NetanelBasal  try checking how you are sharing if privately or publicly .... or anyway try to find out where you are sharing, looks weird...

**Comment by NetanelBasal** [comment]
Ok, but the popup should auto close after the sharing?

**Comment by 45kb** [comment]
For sure, but it's up to the social providers to close it after, we can't do much for that.

**Comment by NetanelBasal** [comment]
But in facebook you have the redirect url that open in the popup after the share is success, this is a problem.

**Comment by 45kb** [comment]
https://gitter.im/720kb/angular-tooltips

**Comment by TheWrongAlice** [comment]
Then redirect to a page with a javascript that closes the window - this is what I do

**Comment by NetanelBasal** [comment]
But i need the reference to the window no?

**Comment by 45kb** [comment]
Didn't checked this but have you tried without specifing a redirect url at all?

**Comment by NetanelBasal** [comment]
Requires valid redirect URI.

**Comment by 45kb** [comment]
Ok :/

**Comment by TheWrongAlice** [comment]
I can post my code when I get to my computer :)

**Comment by 45kb** [comment]
What about this ```'&redirect_uri=' + encodeURI(data.redirectUri);``` to ```'&redirect_uri=' + encodeURIcomponent(data.redirectUri);```

Sure @TheWrongAlice  no problems

**Comment by NetanelBasal** [comment]
Same....

**Comment by NetanelBasal** [comment]
Check this plugin, here the facebook pop up is closing after the share: http://sharebutton.co/

**Comment by 45kb** [comment]
I see no redirect url in the popup at the link you gave me

**Comment by NetanelBasal** [comment]
I need to go now but i will dive in the code of this plugin tomorrow to see what your are missing, you are welcome to do this too :)

**Comment by 45kb** [comment]
@NetanelBasal  awesome, thank you, anyway guys if you want a live support or talking better here https://gitter.im/720kb/angular-socialshare  just ping me or one of the other guys also if you see us offline we'll be in touch quickly :)


You're welcome :dancers:

**Comment by 45kb** [comment]
Anyway i actually trying to find out where _redirect_url_ is declared obbligatory field, i really think it is optional and should be optional in the module too ....... :8ball:

**Comment by TheWrongAlice** [comment]
@45kb you can see it declared as required here: https://developers.facebook.com/docs/sharing/reference/feed-dialog/v2.4

**Comment by TheWrongAlice** [comment]
@NetanelBasal @45kb this is my working implementation:

Call to directive:
```
      <a class="facebook" title="facebook"
         socialshare
         socialshare-provider="facebook"
         socialshare-type="feed"
         socialshare-via="{{shareOpts.fbAppId}}"
         socialshare-media="{{shareOpts.image}}"
         socialshare-text="{{shareOpts.text}}"
         socialshare-caption="{{shareOpts.caption}}"
         socialshare-url="{{shareOpts.url}}"
         socialshare-redirect-uri="http://www.mydomain.com/close.html"></a>
``` 
close.html:
```
<!DOCTYPE html>
<html><body><script>window.close()</script></body></html>
```

This works perfectly for me, afaik

**Comment by NetanelBasal** [comment]
Ok thanks i will try and let you know.

**Comment by 45kb** [comment]
@TheWrongAlice  i still reading this on that page: ```The URL to redirect to after a person clicks a button on the dialog. Required when using URL redirection.``` required WHEN using URL redirection :dancers:  ....

**Comment by NetanelBasal** [comment]
You can check please if facebook and linkedin auto inject your meta description in the pop up?

**Comment by 45kb** [comment]
@NetanelBasal  paste your url here https://developers.facebook.com/tools/debug/ you'll see all the information crawled

**Pull request merged**
