### PR TITLE
fix(): #134 iOS whatsapp and facebook-messenger share on iframe

### PR DESCRIPTION
**Pull request by alonronin**

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @alonronin stunning job!

Just one question before to merge this, did you test this without using the iframe yes? it works without the iframe, right?

**Comment by alonronin** [comment]
yes, we use it at production :smiley:

**Comment by 45kb** [comment]
Awesome 👍  I'll merge and release it, thank you!

**Comment by 45kb** [comment]
Shipped 📦   you just have to install the newest  `2.2.5` version

**Pull request merged**
