### PR TITLE
Adding subreddit support for reddit

### PR DESCRIPTION
**Pull request by ishansharma**
1. Takes value from socialshare-subreddit
2. Made minimum width and height for reddit share to 900 x 650 (reddit being non-responsive, the popup is all messed up at default 500 x 500.

### CODE REVIEW

**Comment by 45kb** [comment]
@ishansharma  Could you just please update the README file to specify how the new attribute works?

thank you a lot!

**Comment by ishansharma** [comment]
@45kb Just added instructions at the end with a note about resolution. Works?

**Comment by 45kb** [comment]
Super awesome @ishansharma  thank you, seriously!

**Comment by ishansharma** [comment]
@45kb My pleasure. Yours was the simple sharing module available and we are using it for http://epicbeat.epictions.com/ 

Glad to be able to contribute back. :)

**Comment by 45kb** [comment]
@ishansharma You're welcome anytime here!

**Pull request merged**
