### PR TITLE
feat(facebook):share dialog is added.

### PR DESCRIPTION
**Pull request by rajathms**
A Share dialog [Facebook-Share-Dialog](https://developers.facebook.com/docs/sharing/reference/share-dialog) and it's parameters (title,hashtag,quote,href) is added.

### CODE REVIEW

**Comment by 45kb** [comment]
Hi, sorry for delay, i reviewed your changes but it looks like you added an already existent feature, facebook dialog is already there https://github.com/720kb/angular-socialshare#facebook

You just have to set socialsare-type="dialog" in order to use it

Am i missing something?

thank you

**Comment by rajathms** [comment]
@45kb yea I accept it's there, which will take the URL type as sharer.

Facebook has three dialog types as feed, send and share till now you had feed and send  and one more else condition sharer , **now I added** [Share-Dialog](https://developers.facebook.com/docs/sharing/reference/share-dialog).
The reason I added this because  from type feed user can't share as a page manager or in the group, for that you have one more type sharer, but in that sharer type, I could not add custom media/text. 

So when I checked facebook documentation, I found one more dialog called **[Share-Dialog](https://developers.facebook.com/docs/sharing/reference/share-dialog), which gives people the most flexibility. They can choose where they want to share, including in groups and private messages on Messenger**.

**Comment by 45kb** [comment]
Oh great, didn't know about the dialog share, we have dialog/feed and dialog/send i think you're right dialog/share is missing.

Just wouldn't be better to just switch the endopint url instead of creating a totally new method for it? I bet dialog/send dialog/feed and dialog/share has same params as options, isn't it?

**Comment by 45kb** [comment]
Look here for example https://github.com/720kb/angular-socialshare/blob/master/lib/angular-socialshare.js#L349 you could just ```if (socialshareType === 'dialog') {}``` don't you agree?

**Comment by 45kb** [comment]
Oh SORRY , my bad, you did it here https://github.com/rajathms/angular-socialshare/blob/904a772eedf1ca7e21ff3d5d772b0bc4bcdf5732/lib/angular-socialshare.js#L417 i did not check the whole file, sorry...

So just change ```=== 'share'``` to ```=== 'dialog'``` and i can merge it! thanks

**Comment by rajathms** [comment]
I think share would be the better name, as we are using same naming convention as facebook do.

we are giving user to select the type, by this parameter socialshare-type=""	(feed,share,send). 
Thinking to fallow the same.

If you want me to change, i will change it.

thank you

**Comment by rajathms** [comment]
@45kb  What you say ?

**Comment by 45kb** [comment]
@rajathms I say ok, you're right :)

Please rechecked the PR and i'll merge, looks everything clear now, thank you

**Comment by rajathms** [comment]
@45kb  Yes, everything is fine. You can merge it :+1: 
Thank You  :)

**Comment by 45kb** [comment]
It has conflicts unfortunately

**Comment by rajathms** [comment]
@45kb  I should not including these dist files right ?

I should send only lib/angular-socialshare.js .

**Comment by 45kb** [comment]
@rajathms to remove conflicts you must just pull the recent commits, check if everythings working again, and resubmit the pr 👍

**Comment by 45kb** [comment]
dist files are rebuilt everytime we release a new version so don't worry

**Comment by rajathms** [comment]
@45kb  updated :+1:  

you can merge it :)

thank you

**Comment by 45kb** [comment]
Thank you @rajathms you can now try the 2.3.3 version which includes your changes, let me know if everything working for you, thanks https://github.com/720kb/angular-socialshare/releases/tag/2.3.3

**Comment by rajathms** [comment]
@45kb  I tried 2.3.3 version, it works awesomely :+1:

**Pull request merged**
