### PR TITLE
Fixing URL Sharing for Addresses Including # Sign

### PR DESCRIPTION
**Pull request by ishansharma**
`encodeURI()` was being used for URLs. This does not encode the hash
sign in URL and as a result, the URLs containing # will break.

To fix this, I just replaced `encodeURI()` with `encodeURIComponent()` which
encodes #.

e.g. Our angular app has URLs in format `http://example.com/#/page-1` .
Everything after hash disappeared.

### CODE REVIEW

**Comment by wouldgo** [comment]
Hi,

I imagine that this PR could be viewed as #8 continuation. Am I rigth?
Thanks for you commitment.

**Comment by ishansharma** [comment]
Hi, 

Yes, I didn't noticed the URL thing at that time. Recently ran into this, so fixed for all networks. Not sure if we should replace other `encodeURI()`s as well, so just replaced the ones that have URLs. 

Thanks.

**Comment by 45kb** [comment]
@ishansharma  Thank you a lot, i will release it in the new version in few hours, so that will be available for all!

**Comment by 45kb** [comment]
done, https://github.com/720kb/angular-socialshare/releases/tag/0.1.6

**Pull request merged**
