### PR TITLE
sms share

### PR DESCRIPTION
**Pull request by shaibo10**
sms share feature added

### CODE REVIEW

**Comment by 45kb** [comment]
Thanks @shaibo10 very great job, i'll release this asap.

**Comment by 45kb** [comment]
Please review it https://github.com/720kb/angular-socialshare/releases/tag/2.2.9 i made some changes

- Removed socialshareUrl which is part of socialshareText if you want
- Remove .replace('%', 'percent') which actually didn't make much sense !?

Thanks

**Comment by shaibo10** [comment]
> Remove .replace('%', 'percent') that, actually, doesn't make much sense !?
I know, but it fix a bug, 
Please try to send sms with '%' sign and see it
Thanks!

**Comment by 45kb** [comment]
Looks ok to me, what is the bug, can you explain  please?

thanks

**Comment by 45kb** [comment]
Oh ok you mean, if i put % sign in the text to share there will be  problem, indeed... i revert this  i really didn't think about that.

**Comment by shaibo10** [comment]
Cool, thanks for the fast response

**Comment by 45kb** [comment]
Actually, this is a problem because it should work when uri encoded, otherwise people who don't speak english will see "percent" in their messages... i am thinking about it and testing this out....

you're welcome

**Comment by shaibo10** [comment]
1. OK, I thought about the percent issue, and I think that the best fix is to replace the '%' with empty string.

2. About the url attribute, I think that if we are in the context of sharing, we need to share something, not a text, but a URL page.
We can compare it to the other share components and see that it fits, the URL attribute is always used for share him.

What do you think about my suggestions?

**Comment by 45kb** [comment]
@shaibo10 both ok for me, just later we have to think how to do for % because both replacing with an holder and deleting them is not correct at all.... very strange this behavior.....

**Pull request merged**
