### PR TITLE
Changing encodeURI() to encodeURIComponent() to allow has inside tweets

### PR DESCRIPTION
**Pull request by ishansharma**
Issue: https://github.com/720kb/angular-socialshare/issues/7

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @ishansharma  first of all thank you for the PR,  i want to merge this, could you please remove dist/ files from the PR?

thank you

**Comment by wouldgo** [comment]
Merged. The issue about dist files that @45kb states is a misunderstanding about our deployment process.

Thanks a lot for your contribuition.

**Comment by 45kb** [comment]
@ishansharma sorry for that, it's everything ok, thank you!

**Comment by ishansharma** [comment]
@wouldgo @45kb No issues. Thanks for merging. :)

**Pull request merged**
