### PR TITLE
fix for configure parameter array containing multiple provider objects

### PR DESCRIPTION
**Pull request by cobyan**
plus, renamed popup windows to keep them separated and prevent reuse of same window

### CODE REVIEW

**Comment by 45kb** [comment]
@cobyan Thanks for your time, did you test this and everything working fine yes?

One last thing, don't use camelCase titles such as "facebookSharer" just use something like "Share on <provider>" , even if i was thinking that we should set the popup title via attribute/configProvider i think  i will introduce socialshare-popup-title="" if you will not 👍 

Please let me know and we can merge this PR :)

**Comment by cobyan** [comment]
hello @45kb (are we both italians speaking english?) yes, I tested it with some modifications on the index.html page: removed directive attributes in the html file and put some values in the config object. It seems to work even if some params are not read (like facebook text), but i think this will be another issue.
For the camel case, this is meant to be the *name* of the window, which make it unique when popping many popups, and as far as I remember (and SO confirms here: http://stackoverflow.com/questions/8051811/how-to-show-window-title-using-window-open) it has problems with spaces in IE, but have not tested this.

**Comment by 45kb** [comment]
@cobyan Yes we are all italians, speaking english since it's universal language :)

However, i did not know about IE problems withspaces, can you put only the provider name in the popup title? "Facebook", "Twitter", etc ...

Thank you!

**Comment by 45kb** [comment]
@cobyan  TEXT for facebook is available only for `socialshare-type="feed"` did you tried with `conf: {type: 'feed'}` ?

**Comment by cobyan** [comment]
@45kb thank you :)
yes I tried now, but I get other errors about the domain. I think the url isn't read or something. I'll test more later and let you know in a new issue

**Comment by 45kb** [comment]
@cobyan 👍

**Pull request merged**
